# Generated by Django 5.2.6 on 2025-09-08 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.IntegerField()),
                ('description', models.TextField()),
                ('icon', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('gear', 'Gear'), ('relic', 'Relic'), ('consumable', 'Consumable'), ('powerup', 'Power Up'), ('special', 'Special')], max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
